import type { ToolPlugin } from '../types';

export const toolRegistry: ToolPlugin[] = [
  {
    id: 'yaml-validator',
    name: 'YAML Validator',
    description: 'Validate, format, and inspect YAML files with detailed error reporting',
    route: '/tools/yaml-validator',
    icon: 'FileCode2',
    category: 'validation',
    tags: ['yaml', 'config', 'validation', 'formatting'],
    persistenceKey: 'tool_yaml_validator',
    featured: true,
    color: 'text-green-400',
    gradient: 'from-green-500/20 to-emerald-500/20',
    defaultInput: `# Example YAML\nname: my-service\nversion: "1.0.0"\nconfig:\n  port: 8080\n  debug: false\n  database:\n    host: localhost\n    port: 5432`,
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Validate, prettify, and minify JSON with syntax highlighting',
    route: '/tools/json-formatter',
    icon: 'Braces',
    category: 'validation',
    tags: ['json', 'formatting', 'validation', 'minify'],
    persistenceKey: 'tool_json_formatter',
    featured: true,
    color: 'text-yellow-400',
    gradient: 'from-yellow-500/20 to-amber-500/20',
    defaultInput: `{"name":"devops-hub","version":"1.0.0","config":{"port":8080,"debug":false}}`,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JWT tokens with claim analysis and expiry status',
    route: '/tools/jwt-decoder',
    icon: 'Key',
    category: 'inspection',
    tags: ['jwt', 'auth', 'token', 'security'],
    persistenceKey: 'tool_jwt_decoder',
    featured: true,
    color: 'text-purple-400',
    gradient: 'from-purple-500/20 to-violet-500/20',
  },
  {
    id: 'cron-tester',
    name: 'Cron Tester',
    description: 'Parse cron expressions, get human-readable explanations, and preview next runs',
    route: '/tools/cron-tester',
    icon: 'Clock',
    category: 'analysis',
    tags: ['cron', 'schedule', 'time', 'automation'],
    persistenceKey: 'tool_cron_tester',
    featured: true,
    color: 'text-blue-400',
    gradient: 'from-blue-500/20 to-cyan-500/20',
    defaultInput: '*/5 * * * *',
  },
  {
    id: 'base64-tool',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings instantly',
    route: '/tools/base64',
    icon: 'Binary',
    category: 'conversion',
    tags: ['base64', 'encode', 'decode', 'conversion'],
    persistenceKey: 'tool_base64',
    color: 'text-orange-400',
    gradient: 'from-orange-500/20 to-red-500/20',
  },
  {
    id: 'docker-compose',
    name: 'Docker Compose Previewer',
    description: 'Parse and visualize Docker Compose files — services, ports, volumes, networks',
    route: '/tools/docker-compose',
    icon: 'Container',
    category: 'inspection',
    tags: ['docker', 'compose', 'containers', 'devops'],
    persistenceKey: 'tool_docker_compose',
    featured: true,
    color: 'text-cyan-400',
    gradient: 'from-cyan-500/20 to-blue-500/20',
    defaultInput: `version: '3.8'\nservices:\n  web:\n    image: nginx:alpine\n    ports:\n      - "80:80"\n    volumes:\n      - ./html:/usr/share/nginx/html\n  db:\n    image: postgres:15\n    environment:\n      POSTGRES_DB: myapp\n      POSTGRES_USER: admin\n    ports:\n      - "5432:5432"`,
  },
  {
    id: 'k8s-inspector',
    name: 'Kubernetes Inspector',
    description: 'Inspect Kubernetes manifests — extract resources, containers, images, metadata',
    route: '/tools/k8s-inspector',
    icon: 'Layers',
    category: 'inspection',
    tags: ['kubernetes', 'k8s', 'manifests', 'devops'],
    persistenceKey: 'tool_k8s_inspector',
    color: 'text-indigo-400',
    gradient: 'from-indigo-500/20 to-purple-500/20',
    defaultInput: `apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: my-app\n  namespace: default\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: my-app\n  template:\n    spec:\n      containers:\n      - name: app\n        image: my-app:1.0.0\n        ports:\n        - containerPort: 8080`,
  },
  {
    id: 'env-diff',
    name: 'Env Diff Checker',
    description: 'Compare .env files side-by-side and highlight added, removed, and changed keys',
    route: '/tools/env-diff',
    icon: 'GitCompare',
    category: 'analysis',
    tags: ['env', 'diff', 'comparison', 'configuration'],
    persistenceKey: 'tool_env_diff',
    color: 'text-pink-400',
    gradient: 'from-pink-500/20 to-rose-500/20',
  },
  {
    id: 'curl-converter',
    name: 'cURL Converter',
    description: 'Convert cURL commands to fetch, axios, and other HTTP client formats',
    route: '/tools/curl-converter',
    icon: 'ArrowLeftRight',
    category: 'conversion',
    tags: ['curl', 'http', 'fetch', 'axios', 'api'],
    persistenceKey: 'tool_curl_converter',
    color: 'text-teal-400',
    gradient: 'from-teal-500/20 to-cyan-500/20',
  },
  {
    id: 'log-analyzer',
    name: 'Log Analyzer',
    description: 'Analyze application logs — highlight severity, count patterns, group errors',
    route: '/tools/log-analyzer',
    icon: 'ScrollText',
    category: 'analysis',
    tags: ['logs', 'debugging', 'analysis', 'monitoring'],
    persistenceKey: 'tool_log_analyzer',
    featured: true,
    color: 'text-red-400',
    gradient: 'from-red-500/20 to-orange-500/20',
  },
];

export const getFeaturedTools = () => toolRegistry.filter((t) => t.featured);
export const getToolsByCategory = (category: string) =>
  toolRegistry.filter((t) => t.category === category);
export const getToolById = (id: string) => toolRegistry.find((t) => t.id === id);
